name: Build LaTeX document
on:
  push:
    tags:
      - "*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          docker_image: ghcr.io/xu-cheng/texlive-full:20240315
          root_file: |
            cv.tex
            resume.tex
          latexmk_use_xelatex: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv.pdf
            resume.pdf
